version: '3'
services:
  postgres:
    image: postgres
    container_name: my-postgres-container
    environment:
      POSTGRES_USER: nick
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: quickbooks
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  typescript-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3000:3000"
volumes:
  postgres-data:
